service: selenium-layer

provider:
  name: aws
  runtime: python3.7
  region: ap-southeast-2
  timeout: 900

layers:
  chromedriver:
    path: chromedriver
    description: chrome driver layer
    compatibleRuntimes:
      - "python3.6"
resources:
  Outputs:
    ChromedriverLayerExport:
      Value:
        Ref: ChromedriverLambdaLayer
      Export:
        Name: ChromedriverLambdaLayer
